// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdtlydpkywvmeqeuewuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkdGx5ZHBreXd2bWVxZXVld3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTcwNDMsImV4cCI6MjA2ODM3MzA0M30.hoIfqE9-m-nv3pK7CyoZ5elXo_yIMslMZAWWXTNQHeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});